swagger: "2.0"
info:
  description: "Esta api,es de tipo CRUD y permite administrar los colores.
  La api maneja 2 niveles de restriccion, segun los perfiles USUARIO y ADMINISTRADOR"
  version: "1.0.0"
  title: "Api colores"
  contact:
    email: "orlando.luis.dpf@gmail.com"
  license:
    name: "Desarollada en Nodejs"
host: "localhost:27017"
basePath: "/"
tags:
- name: "color"
  description: "Everything about your Colors CRUD"
- name: "user"
  description: "Operations about user"
schemes:
- "http"
paths:
  /color:
    post:
      tags:
      - "color"
      summary: "Add a new color"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Color object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Color"
      responses:
        default:
          description: "successful operation"
    put:
      tags:
      - "color"
      summary: "Update an existing color"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Color object that needs to update"
        required: true
        schema:
          $ref: "#/definitions/Color"
      responses:
        default:
          description: "successful operation"
  /color/page:
    get:
      tags:
      - "color"
      summary: "Finds colors"
      description: "Multiple colors"
      produces:
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        required: true
        type: "array"
        items:
          type: "string"
      responses:
        default:
          description: "successful operation"
  /color/{idColor}:
    get:
      tags:
      - "color"
      summary: "Find color by ID"
      description: "Returns a single color"
      produces:
      - "application/json"
      parameters:
      - name: "idColor"
        in: "path"
        description: "ID of color to return"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
    delete:
      tags:
      - "color"
      summary: "Deletes a color"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        required: true
        type: "string"
      - name: "idColor"
        in: "path"
        description: "Color id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        default:
          description: "successful operation"
  /user:
    post:
      tags:
      - "user"
      summary: "Search user"
      description: "This can only be done by the logged in user."
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
definitions:
  User:
    type: "object"
    properties:
      user:
        type: "string"
      perfil:
        type: "string"
  Color:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "sand dollar"
      color:
        type: "string"
        example: "#DECDBE"
      pantone:
        type: "string"
        example: "13-1106"        
      year:
        type: "string"
        example: "2006"         
        